# Generated by Django 3.2 on 2021-10-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_lessons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lessons',
            new_name='Lesson',
        ),
    ]
